# Base config
title: Meteoros Floripa
description: Estações de capturas de meteoros em Florianópolis/SC
url: "https://meteoros.floripa.br"
baseurl: "/"
city: "Florianópolis-SC"

# Jekyll configurations
encoding: UTF-8
highlighter: rouge
timezone: UTC
permalink: pretty
limit_posts: 24
incremental: true

# Maintenance mode
maintenance: false

# Tools config
simple_form_token: 5da33a3875b2782c0143c966613ebc60

# Jekyll plugins enabled
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Collections to build
collections:
  captures:
    output: true

  stations:
    output: true

  watches:
    output: true

# Feed config
feed:
  icon: /assets/favicon.png
  logo: /assets/logo.png
  disable_in_development: true
