# Base config
title: Meteoros Floripa
description: Estações de capturas de meteoros em Florianópolis/SC
url: "https://meteoros.floripa.br"
baseurl: "/"
city: "Florianópolis-SC"

# Jekyll configurations
encoding: UTF-8
highlighter: rouge
timezone: UTC
permalink: pretty
limit_posts: 24
incremental: true

# Maintenance mode
maintenance: true

# Tools config
simple_form_token: 5da33a3875b2782c0143c966613ebc60

# Build config
build:
  days: 2
  captures:
    - "C:/bramon/!data"
  stations:
    - TLP1
    - TLP2
  converter:
    path: "C:/bramon/tools/ffmpeg.exe"
  storage:
    url: "https://storage.meteoros.floripa.br/"
    captures: "E:/capturas"
    videos: "E:/capturas/videos"

# Jekyll exclude from build
exclude:
  - bin
  - venv
  - Makefile

# Jekyll plugins enabled
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Collections to build
collections:
  captures:
    output: true

  stations:
    output: true

  watches:
    output: true

# Feed config
feed:
  icon: /assets/favicon.png
  logo: /assets/logo.png
  disable_in_development: true
