# Base config
title: Meteoros Floripa
description: Estações de capturas de meteoros em Florianópolis/SC
url: "https://meteoros.floripa.br"
baseurl: "/"
city: "Florianópolis-SC"
encoding: UTF-8
highlighter: rouge
timezone: UTC
permalink: pretty
paginate: 24
pagination_path: "/:num"
limit_posts: 24
incremental: true

# Tools config
google_analytics: "UA-148905542-1"
simple_form_token: 5da33a3875b2782c0143c966613ebc60
ffmpeg_path: "C:/bramon/tools"

# Storage config
storage:
  url: "https://storage.meteoros.floripa.br/"
  captures: "D:/BRAMON"
  videos: "D:/Meteoros"

# Build config
build:
  days: 2
  captures:
    - "C:/bramon/!data"

# Stations enabled
stations:
  - TLP1
  - TLP2

# Jekyll config
exclude:
  - bin

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji

sass:
  style: compressed

collections:
  captures:
    output: true

  stations:
    output: true

  watches:
    output: true
